fix bash scripts format to follow same as shfmt

diff --git a/template/hacks/verify-gofmt b/template/hacks/verify-gofmt
--- a/template/hacks/verify-gofmt
+++ b/template/hacks/verify-gofmt
@@ -7,8 +7,8 @@ GOFMT="gofmt -s -w"
 
 bad_files=$($GOFMT -l *.go)
 if [[ -n "${bad_files}" ]]; then
-  echo "FAIL: '$GOFMT' needs to be run on the following files: "
-  echo "${bad_files}"
-  echo "FAIL: please execute make gofmt"
-  exit 1
+	echo "FAIL: '$GOFMT' needs to be run on the following files: "
+	echo "${bad_files}"
+	echo "FAIL: please execute make gofmt"
+	exit 1
 fi
diff --git a/template/hacks/verify-goimports b/template/hacks/verify-goimports
--- a/template/hacks/verify-goimports
+++ b/template/hacks/verify-goimports
@@ -7,8 +7,8 @@ GOIMPORTS="goimports -w"
 
 bad_files=$($GOIMPORTS -l *.go)
 if [[ -n "${bad_files}" ]]; then
-  echo "FAIL: '$GOIMPORTS' needs to be run on the following files: "
-  echo "${bad_files}"
-  echo "FAIL: please execute make gofmt"
-  exit 1
+	echo "FAIL: '$GOIMPORTS' needs to be run on the following files: "
+	echo "${bad_files}"
+	echo "FAIL: please execute make gofmt"
+	exit 1
 fi
